name: Sonarqube

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonarqube:
    name: Sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Sonarqube analysis
        run: echo "Running Sonarqube analysis..."
